title: Steins Parallel Line Created ?
author: Supashey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Steins created a parallel World through a Gate which eventually went ahead of time and was known as Steins:Gate.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
